version: '3'
services:
  web:
    build: .
    command: /bin/sh -c "python manage.py collectstatic --noinput; python manage.py makemigrations --noinput; python manage.py migrate; gunicorn AthenaPhoto.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - ./AthenaPhoto:/home/AthenaPhotoProject
    expose:
      - 8000
    
  nginx:
    build: ./nginx
    volumes:
      - ./AthenaPhoto/static_cdn/static_root:/home/AthenaPhotoProject/AthenaPhoto/static_cdn/static_root
      - ./AthenaPhoto/static_cdn/media_root:/home/AthenaPhotoProject/AthenaPhoto/static_cdn/media_root
    ports:
      - 9001:80
    depends_on:
      - web

