# Generated by Django 4.0 on 2021-12-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_picture_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
