# Generated by Django 4.0 on 2021-12-22 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_picture_taken_at_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
