# Generated by Django 4.0 on 2021-12-23 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
