# Generated by Django 4.0 on 2021-12-23 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_picture_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='description',
        ),
    ]
